"""
Form Builder Agent — TRD §3.2, Workflow Stage 2.

Turns a RequisitionDraft (requirement_parser.py) into a candidate-facing
application form matching `forms.form_schema` (06-Backend-Schema.md §2.3).
Routed through the LLM Router under Task.FORM_GENERATION — reasoning tier,
same as requirement parsing (this is structured creative generation, not a
high-volume lookup).

Split between hardcoded and LLM-generated fields, deliberately:

- Baseline fields (language preference, name/email/phone, resume upload,
  availability, and the AI-disclosure notice) are defined in code, not
  generated by the model. The disclosure notice is the PRD/UI-UX-mandated
  copy verbatim — there must be no path by which a model paraphrase could
  drift from the approved wording — and the rest are structurally identical
  across every requisition, so there's nothing for an LLM to usefully add by
  regenerating them fresh each time. TRD lists "resume upload, basic info,
  skill self-assessment, availability, language preference" as this agent's
  output; four of those five are exactly this fixed set.
- Only the genuinely role-specific parts — one self-assessment question per
  required skill, and a short eligibility-check question per
  eligibility_rules entry — are generated by the LLM, since those actually
  vary by role and benefit from natural phrasing over a robotic per-skill
  template. If a requisition has no skills or eligibility rules stated, the
  LLM call is skipped entirely — nothing role-specific to generate, so
  there's no reason to spend a request on it.

Same pure-function shape as requirement_parser.py: struct in, validated
struct out, no Supabase write — see that module's docstring for why. Owner
approval (TRD §3.2: "one-click approve, not silent auto-publish") is a
UI/API-layer concern; this agent only ever produces a *draft* form_schema.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ValidationError, model_validator

from app.agents._shared import JSONExtractionError, extract_json
from app.agents.requirement_parser import RequisitionDraft
from app.connectors.llm_router import Task, generate

# Exact copy from 04-UIUX-Design-Brief.md §5.1 — the mandated candidate-facing
# AI-disclosure notice. A constant, not a prompt instruction, so there is no
# path by which a model paraphrase could drift from the approved wording.
AI_DISCLOSURE_NOTICE = (
    "Your application may be reviewed by AI, and if shortlisted, your first "
    "interview will be conducted by an AI interviewer over video call. "
    "A recruiter reviews every decision."
)


class FieldType(str, Enum):
    TEXT = "text"
    EMAIL = "email"
    TEL = "tel"
    FILE = "file"
    SELECT = "select"
    RADIO = "radio"
    TEXTAREA = "textarea"
    NOTICE = "notice"  # informational text block, not an input


class FormField(BaseModel):
    field_id: str
    label: str
    field_type: FieldType
    required: bool = True
    options: list[str] | None = None
    help_text: str | None = None


class FormSchema(BaseModel):
    """Matches `forms.form_schema` (JSONB) directly via `.model_dump()` —
    same "one shape, no translation layer" reasoning as RequisitionDraft."""

    fields: list[FormField]

    @model_validator(mode="after")
    def _field_ids_must_be_unique(self) -> "FormSchema":
        """
        Catches two distinct failure modes with one check: the model
        generating a duplicate field_id across its own dynamic fields, or
        generating one that collides with a reserved baseline field_id
        (e.g. a skill happening to be phrased into "email" or "resume").
        Either way a duplicate key means one field would silently overwrite
        another wherever this schema gets rendered as a form-data dict —
        making it an unrepresentable state here means that failure surfaces
        immediately as FormBuildError, not as a silently half-broken form.
        """
        seen: set[str] = set()
        for f in self.fields:
            if f.field_id in seen:
                raise ValueError(f"duplicate field_id: {f.field_id!r}")
            seen.add(f.field_id)
        return self


class FormBuildError(Exception):
    """
    Raised only when the model's response for the dynamic (role-specific)
    fields can't be turned into a valid form — the baseline fields are plain
    Python and can't fail this way. If this is raised, the failure is always
    in the LLM-generated portion, never the compliance-critical baseline.
    """

    def __init__(self, detail: str, raw_response: str):
        self.detail = detail
        self.raw_response = raw_response
        super().__init__(f"Failed to build form: {detail}")


def _baseline_fields() -> list[FormField]:
    return [
        FormField(
            field_id="language_preference",
            label="Preferred language",
            field_type=FieldType.SELECT,
            required=True,
            options=["English", "हिंदी (Hindi)", "मराठी (Marathi)"],
        ),
        FormField(
            field_id="ai_disclosure_notice",
            label=AI_DISCLOSURE_NOTICE,
            field_type=FieldType.NOTICE,
            required=False,
        ),
        FormField(field_id="full_name", label="Full name", field_type=FieldType.TEXT, required=True),
        FormField(field_id="email", label="Email address", field_type=FieldType.EMAIL, required=True),
        FormField(field_id="phone", label="Phone number", field_type=FieldType.TEL, required=True),
        FormField(
            field_id="resume",
            label="Resume",
            field_type=FieldType.FILE,
            required=True,
            help_text="PDF preferred.",
        ),
        FormField(
            field_id="availability",
            label="When are you available to start?",
            field_type=FieldType.TEXT,
            required=True,
        ),
    ]


_DYNAMIC_FIELDS_INSTRUCTIONS = """\
You are the Form Builder for a hiring assistant. Given a job requisition, \
generate ONLY the role-specific candidate-facing form fields:
- One self-assessment question per required skill.
- At most one short eligibility-check question per distinct entry in \
eligibility_rules, if any are stated.

Do NOT include name, email, phone, resume, language, or availability fields \
— those are added automatically and are not your job to generate.

Output JSON matching exactly this shape:

{
  "fields": [
    {
      "field_id": string (snake_case, unique, stable key),
      "label": string (the question shown to the candidate),
      "field_type": "select" | "radio" | "text" | "textarea",
      "required": boolean,
      "options": array of strings or null (required for select/radio, null otherwise),
      "help_text": string or null
    }
  ]
}

Rules:
- One field per required skill, phrased as a natural self-assessment — pick \
whichever field_type fits the skill best, not always the same template.
- Keep every label warm and plain-language; candidates applying are often \
freshers/interns.
- Output ONLY the JSON object. No commentary, no markdown code fences.

Requisition:
role_title: {role_title}
required_skills: {required_skills}
eligibility_rules: {eligibility_rules}
"""


def _build_prompt(requisition: RequisitionDraft) -> str:
    # Plain substring replace, not str.format() — same reason as
    # requirement_parser.py: the template contains literal JSON braces.
    return (
        _DYNAMIC_FIELDS_INSTRUCTIONS.replace("{role_title}", requisition.role_title)
        .replace("{required_skills}", ", ".join(requisition.required_skills) or "(none stated)")
        .replace("{eligibility_rules}", str(requisition.eligibility_rules) or "(none stated)")
    )


def build_form(requisition: RequisitionDraft) -> FormSchema:
    """
    The single entry point. Raises FormBuildError on a genuine failure in the
    LLM-generated dynamic fields, including a generated field colliding with
    a reserved baseline field_id. Does NOT catch AIQuotaExhausted — same
    reasoning as requirement_parser.parse_requirement: that's the caller's
    responsibility (TRD §3.1a / app/core/quota_guard.py), not this agent's.
    """
    fields = _baseline_fields()
    # No LLM call at all if there's nothing role-specific to generate — also
    # what the final ValidationError branch below falls back to describing,
    # since `result` only exists when this branch actually ran.
    raw_model_output = "(no LLM call made — baseline fields only, nothing role-specific to generate)"

    if requisition.required_skills or requisition.eligibility_rules:
        result = generate(_build_prompt(requisition), task=Task.FORM_GENERATION)
        raw_model_output = result.text

        try:
            payload = extract_json(result.text)
        except JSONExtractionError as exc:
            raise FormBuildError(exc.detail, exc.raw_response) from exc

        try:
            dynamic = FormSchema.model_validate(payload)
        except ValidationError as exc:
            raise FormBuildError(f"model output didn't match the required schema: {exc}", result.text) from exc

        fields.extend(dynamic.fields)

    try:
        return FormSchema(fields=fields)
    except ValidationError as exc:
        # Reached only if a generated field_id collided with a baseline one
        # (the _field_ids_must_be_unique validator) — everything else about
        # the baseline fields is fixed, known-valid Python.
        raise FormBuildError(f"generated fields conflicted with the form schema: {exc}", raw_model_output) from exc
